CREATE TABLE "Ambitos" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT);
CREATE TABLE "AmbitosxGrupo" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "idAmbito" INTEGER REFERENCES "Ambitos" ("_id"), "idGrupo" INTEGER REFERENCES "Cursos" ("idCurso"));
CREATE TABLE "Fechas" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "Fecha" TEXT, "nombre" TEXT);
CREATE TABLE "Grupos" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "año" INTEGER);
CREATE TABLE "Habilidades" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "esPositiva" BOOLEAN);
CREATE TABLE "HabilidadesxJanij" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "idFecha" TEXT REFERENCES "Fechas" ("_id"), "idAmbito" TEXT REFERENCES "Ambitos" ("_id"), "idGrupo" TEXT REFERENCES "Grupos" ("_id"), "idJanij" TEXT REFERENCES "Janijim" ("_id"), "idHabilidad" TEXT REFERENCES "Habilidades" ("_id"), "Observaciones" TEXT);
CREATE TABLE "Janijim" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "apellido" TEXT, "dni" INTEGER);
CREATE TABLE "JanijimxGrupo" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "idJanij" INTEGER REFERENCES "Janijim" ("_id"), "idGrupo" INTEGER REFERENCES "Grupos" ("_id"));
CREATE TABLE "Presentismo" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "Alumno" INTEGER REFERENCES "Alumnos" ("idAlumno"), "Fecha" INTEGER REFERENCES "Fechas" ("idFecha"), "idGrupo" INTEGER REFERENCES "Grupos" ("_id"), "idAmbito" INTEGER REFERENCES "Ambitos" ("_id"), "asistio" BOOLEAN, "tarde" BOOLEAN);
INSERT INTO "Ambitos" ( "_id","nombre" ) VALUES ( '1','Sabado' );
INSERT INTO "Ambitos" ( "_id","nombre" ) VALUES ( '2','Viernes' );
INSERT INTO "Ambitos" ( "_id","nombre" ) VALUES ( '3','Curso de madrijim' );
INSERT INTO "Fechas" ( "_id","Fecha","nombre" ) VALUES ( '1','2017/10/25','' );
INSERT INTO "Fechas" ( "_id","Fecha","nombre" ) VALUES ( '2','2017/10/26','' );
INSERT INTO "Fechas" ( "_id","Fecha","nombre" ) VALUES ( '3','2017/10/27','' );
INSERT INTO "Habilidades" ( "_id","nombre","esPositiva" ) VALUES ( '1','Hizo la actividad','true' );
INSERT INTO "Habilidades" ( "_id","nombre","esPositiva" ) VALUES ( '2','Molesto a los companeros','false' );
INSERT INTO "Habilidades" ( "_id","nombre","esPositiva" ) VALUES ( '3','Respeto a los madrijim','true' );
INSERT INTO "Habilidades" ( "_id","nombre","esPositiva" ) VALUES ( '4','Rompio los materiales','false' );
